### ISSUE TITLE
add explicit module version-stmt

### ISSUE THREAD

**Issue by abierman** [netmod-wg/yang-next#20]
The module revision date is not actually included.
It is the most recent date of the revision-stmt date strings.
It would be useful for module readers and module parser tools
to determine the module version in 1 simple statement, before
the linkage-stmts and other header info.

  module foo {
      yang-version 1.2;
      module-version 2017-03-13;
      ....  lots of header lines
      revision 2017-03-13 { ... }
      ...
 }

**Comment by schoenw** [comment]
Redundant data tends to cause problems. What is the issue with finding the first revision statement?

**Comment by kwatsen** [comment]
This issue should be resolved by the netmod versioning DT work

**Comment by kwatsen** [comment]
Closed by #45
