### ISSUE TITLE
add a 'backwards-compatibility' leaf to 'revision' statement?

### ISSUE THREAD

**Issue by kwatsen** [netmod-wg/yang-next#24]
Per YANG update rules, YANG modules are supposed to be forever backwards compatible, but this approach doesn't always work in practice.  For instance, for a vendor that generates so-called "native" models, the module-names effectively *must* be the same over time, but backwards-compatibility cannot be guaranteed.

As an adjunct to this, it would be nice if the parts of the tree that are not backwards-compatible could be called out, so clients can determine if the break(s) in compatibility matters to them.

**Comment by schoenw** [comment]
I think this is part of the versioning work these days.

**Comment by kwatsen** [comment]
Closed during Feb 6 Virtual Interim meeting.

Versioning solution ( Issue #45 ) to address this.
