### ISSUE TITLE
make yang more object-oriented

### ISSUE THREAD

**Issue by kwatsen** [netmod-wg/yang-next#25]
Lada writes: I agree that there is a close alignment but then I guess NETMOD should have started with a different approach, perhaps object-oriented rather than document-oriented, where configuration could play the role of "methods" intended for changing the object's state. (If Randy Presuhn was reading this, he would probably refer to certain ancient technologies at this point.:-)

**Comment by immibis** [comment]
If it was object-oriented, how would you apply atomic updates for example?

**Comment by sunseawq** [comment]
The method role can also be played by Action. unfortunately action is only invoked on operational state datastore, which I think is unfortuantely. To follow object orient approach, we should also introduce object method in the UML diagram and specify how such method is handled in handled in the context of configuration datastore.

**Comment by BalazsLengyel** [comment]
Remember https://tools.ietf.org/html/rfc6095

**Comment by schoenw** [comment]
There is an RFC and I do not think it got much traction. I suggest to reject this.

**Comment by mbj4668** [comment]
I agree with Juergen.  This would be a new language imo.

**Comment by kwatsen** [comment]
Closed during Feb 6 Virtual Interim meeting.
