### ISSUE TITLE
Allow prefix statement to be optional for modules that don't need it

### ISSUE THREAD

**Issue by kwatsen** [netmod-wg/yang-next#3]
Currently the prefix statement is required, but many modules do not ever refer it, and other modules that import the module can give the module another prefix value anyway.   It would be nice to change to cardinality of the prefix statement from "1" to "0..1".

**Comment by abierman** [comment]
This won't work because the parser will think
no prefix means it is defined in the current module (and/or all submodules)

**Comment by tonydamage** [comment]
@kwatsen : You mean prefix statement as default prefix in module not in import-stmt?

**Comment by schoenw** [comment]
I doubt that not having to define a prefix gives us a real boost of YANG productivity. And you never know what is going to refer to a module eventually.

**Comment by BalazsLengyel** [comment]
Don't like the idea.
If multiple modules import, I would like them to use the same prefix.

**Comment by kwatsen** [comment]
having a common prefix is helpful
