### ISSUE TITLE
YANG ANBF could be defined in a simpler way

### ISSUE THREAD

**Issue by rgwilton** [netmod-wg/yang-next#37]
The current YANG ABNF is quite long and encodes all the possible different rules and values, and allowed substmts.

However, when writing YANG parsers, the ABNF has been less useful that I would expect.  The parsers that I have written generically parse the structure of a YANG file (which is quite simple, e.g. identifier, optional quoted argument, optional substmts) and then separately validate that the argument is valid, only valid substmts are included, the right number of substmts are present, etc.

Possibly, it might be worth considering whether decoupling parsing the general structure vs the parsing the specific arguments may be more useful to implementors.  Of course, it is more questionable whether it is worth the effort of changing this now.

**Comment by llhotka** [comment]
Nn my view, the ABNF in RFC 7950 is useful as a quick reference, e.g. on
permitted substatements of a given statement. I also used it pretty much
directly for constructing the RELAX NG schema of the YIN syntax:

https://github.com/CZ-NIC/yangson/blob/master/tools/relaxng/yin.rng

Of course, writing parsers is a different thing and most parsers I have
seen (or written) indeed use the special general structure of YANG
statements.

**Comment by schoenw** [comment]
I consider this low priority, quite some work, lots of chances to introduce errors, no real value.

**Comment by tonydamage** [comment]
@rgwilton: The simplified ABNF is actually "defined" in YANG specification:
[Section 6.3 Statements](https://tools.ietf.org/html/rfc7950#section-6.3) contains simplified one:

> A YANG module contains a sequence of statements.  Each statement
> starts with a keyword, followed by zero or one argument, followed 
> either a semicolon (";") or a block of substatements enclosed within
> braces ("{ }"):
>
>        statement = keyword [argument] (";" / "{" *statement "}")
>
>  The argument is a string, as defined in Section 6.1.2.

This approach was used in Antlr-based implementation of YANG parser in OpenDaylight Project
See:
[YangStatementLexer.g4](https://github.com/opendaylight/yangtools/blob/master/yang/yang-parser-rfc7950/src/main/antlr/YangStatementLexer.g4)
[YangStatementParser.g4](https://github.com/opendaylight/yangtools/blob/master/yang/yang-parser-rfc7950/src/main/antlr/YangStatementParser.g4)

**Comment by rgwilton** [comment]
@tonydamage: Yes, that is a start, but I was thinking that a slightly more complete definition would be useful.  E.g. this doesn't define what keyword, or argument are, or mention whitespace.

I do agree with Juergen that this is low priority, but I'm not convinced that the full ABNF is actually that useful.

**Comment by rovarga** [comment]
@tonydamage  @rgwilton  I think the current grammar needs to be split up a the very least. Things like schema-node-identifier are always parsed separately and having to split them/copy&paste them is not convenient for implementations. Would it make sense to contribute lexer and grammar definitions to https://github.com/antlr/grammars-v4/ in a modular fashion, so parser across languages can just pick them up?

**Comment by mbj4668** [comment]
I agree that the ABNF grammar isn't really useful for parsers directly.  The idea was to have a formal defintion of the legal substatements and arguments.

**Comment by kwatsen** [comment]
Closed during Feb 6 Virtual Interim meeting.
