### ISSUE TITLE
Allow action to be invoked in the context of configuration datastore

### ISSUE THREAD

**Issue by sunseawq** [netmod-wg/yang-next#38]
I see restricting action to be invoked in the context of operational state datastore is very limited. It will be great to allow action to be invoked in the context of configuration datastore, such as allow multiple sub-operations on different conceptual nodes within edit-config, such as batch operation on some conceptual nodes using action, this will help improve efficiency of transaction or NETCONF protocol.

**Comment by schoenw** [comment]
I fail to see why an action on configuration data is useful. I suggest to reject this.

**Comment by BalazsLengyel** [comment]
I support this. 
Actions can be used to modify the running configuration. That is allowed, however modifying running, but calling the action in the context of operational is awkward.

**Comment by schoenw** [comment]
Concrete examples would help me to understand why actions are useful on configuration datastores. I am looking for examples demonstrating that generic edit operations cannot achieve the same effect.

**Comment by BalazsLengyel** [comment]
One example (details from Kent or Balazs Kovacs)  was where security information (list entries) was generated from the TPM module using an action. Later some additional information was configurable for each list-entry.

In some cases actions are used for complex configuration steps, where e.g. you need to configure 5 different leafs in different part of the data tree in the same transaction. This could be done by edit-config, however providing an action makes it more user-friendly., it is an existing use-case.

Anyway it is not critical, but useful. And definitely avoid more restrictions on actions and other datastores.

**Comment by schoenw** [comment]
The TPM module is an operation state thing. You invoke an action on the TPM module and as a side effect the TPM module may generate configuration data. I do not see how this translates to an action on a configuration datastore.

The second example seems to be a "template edit operation" but not really an action that you invoke on configuration data. Perhaps people want additional editing primitives but I am not sure actions are the designed for this.

**Comment by sunseawq** [comment]
batch operation I proposed in netconf inline action draft is to configure trunk interface with vlan range, allow vlan range merging, reduce query times and improve netconf query efficiency. There may have other batch operation example.
发件人： Balazs Lengyel
收件人： netmod-wg/yang-next<yang-next@noreply.github.com<mailto:yang-next@noreply.github.com>>
抄送： Qin Wu<bill.wu@huawei.com<mailto:bill.wu@huawei.com>>;Author<author@noreply.github.com<mailto:author@noreply.github.com>>
主题： Re: [netmod-wg/yang-next] Allow action to be invoked in the context of configuration datastore (#38)
时间： 2018-11-27 18:47:00


One example (details from Kent or Balazs Kovacs) was where security information (list entries) was generated from the TPM module using an action. Later some additional information was configurable for each list-entry.

In some cases actions are used for complex configuration steps, where e.g. you need to configure 5 different leafs in different part of the data tree in the same transaction. This could be done by edit-config, however providing an action makes it more user-friendly., it is an existing use-case.

Anyway it is not critical, but useful. And definitely avoid more restrictions on actions and other datastores.

―

**Comment by mbj4668** [comment]
And the TPM-related action was actually removed b/c of the problems related to having actions towards configuration.

**Comment by sunseawq** [comment]
Action allows the client to describe intent, and the sever does the dirty work. That's why it is user friendly, in my opinion.

Also i think there is requirements to translate learned data into static configuration data. Action can fulfill that.

发件人： schoenw
收件人： netmod-wg/yang-next<yang-next@noreply.github.com<mailto:yang-next@noreply.github.com>>
抄送： Qin Wu<bill.wu@huawei.com<mailto:bill.wu@huawei.com>>;Author<author@noreply.github.com<mailto:author@noreply.github.com>>
主题： Re: [netmod-wg/yang-next] Allow action to be invoked in the context of configuration datastore (#38)
时间： 2018-11-27 19:05:40


The TPM module is an operation state thing. You invoke an action on the TPM module and as a side effect the TPM module may generate configuration data. I do not see how this translates to an action on a configuration datastore.

The second example seems to be a "template edit operation" but not really an action that you invoke on configuration data. Perhaps people want additional editing primitives but I am not sure actions are the designed for this.

―

**Comment by kwatsen** [comment]
Closed during Feb 6 Virtual Interim meeting.
