### ISSUE TITLE
make schema-mount extension into a built-in statement

### ISSUE THREAD

**Issue by llhotka** [netmod-wg/yang-next#42]
This extension affects the resulting schema, so it should be integrated into the language.

**Comment by mbj4668** [comment]
I don't think we should incorporate schema mount into the language until we have had some experience with the current document.

**Comment by kwatsen** [comment]
Possibly solved by "critical" extensions: Issue #49.

**Comment by kwatsen** [comment]
Closed in Feb 6 Virtual Interim meeting.
