### ISSUE TITLE
Support for multiple keys in a list

### ISSUE THREAD

**Issue by Reshad-Rahman** [netmod-wg/yang-next#43]
e.g. if a list is used to map A to B (both unique), we can have key A OR key B OR key A+B. It may be useful to support key A and key B (2 key statements for the list).

**Comment by BalazsLengyel** [comment]
This is like optional keys, which we discarded in YANG 1.1
Optional keys make the world complicated unless there is a default value for the key.

**Comment by Reshad-Rahman** [comment]
If we have 2 key statements neither of them would be optional.

**Comment by schoenw** [comment]
Simply define two lists if you need different keys.

**Comment by Reshad-Rahman** [comment]
I agree the workaround is to define 2 lists, but defining 2 lists with the same data but different keys seems wasteful IMHO.

**Comment by abierman** [comment]
2 lists that use the same grouping can have different key-stmts

**Comment by rovarga** [comment]
agreed, but they are still different instantiations -- and cause hassle with augment.

**Comment by mbj4668** [comment]
What is the problem that you want to solve, or maybe I should ask when is the second key supposed to be used?  Is it important for edit-config?

**Comment by Reshad-Rahman** [comment]
It could be for config or for oper data. Imagine you have a list where A is unique and B is unique. You may want to access an element via A or via B. e.g. take a look at list items in draft-ietf-core-sid. We may want to access the data via namespace+identifier or via sid.
2 lists with groupings would work in the oper case. But how do we handle a config list? And as Robert mentioned, you end up with 2 instances and augments become a pain.

**Comment by kwatsen** [comment]
Martin: is this actually a protocol issue?  Keys are only for unique identification...

Closed in Feb 6 Virtual Interim meeting.
