### ISSUE TITLE
when using a grouping, the designer should be able to modify just about any aspect of the grouping

### ISSUE THREAD

**Issue by kwatsen** [netmod-wg/yang-next#48]
This started in the "removing a node from a grouping" netmod thread, where there was a desire to remove a subtree.

Then, in the "YangPush now" netconf thread, there was a similar interest to disable an "if-feature" statement in the grouping.

Generally, it seems that the module-designer should be able to do just about anything, without having to copy/paste the entire grouping first.

**Comment by immibis** [comment]
At the same time, this could lead to excessive complexity due to the layering.

**Comment by kwatsen** [comment]
Both Rob and Martin are skeptical.

Closed in Feb 6 Virtual Interim meeting.
