### ISSUE TITLE
add a statement for modeling checkbox dialogs

### ISSUE THREAD

**Issue by kwatsen** [netmod-wg/yang-next#52]
A "choice" statement is ideal for modeling a radio-button dialog (i.e., pick one of many):
```
  ( ) foo
  ( ) bar
  (o) baz
```

There should be a statement to model a checkbox dialog (i.e., pick any number of many, but not more than one of each):
```
  [x] foo
  [x] bar
  [x] baz
```

The statement SHOULD have both the "min-elements" and "max-elements" substatements.

**Comment by abierman** [comment]
I like this idea

**Comment by mbj4668** [comment]
How is this different than having a sequence of three optional leafs foo, bar, baz?
I haven't seen the need for a new statement for this situation.

**Comment by kwatsen** [comment]
Correct, 3 optional leafs works at the syntax level, but not quite at the semantic-level.  A generic tool probably wouldn't render a container with a bunch of optional leafs as a checkbox dialog.   

A workaround is the solution described by Issue #51, so that overlay/annotations can be used to drive the UI.

**Comment by immibis** [comment]
A `bits` type?

**Comment by kwatsen** [comment]
Re-opening so it can be scored.

**Comment by kwatsen** [comment]
We feel that solution offer by issue #51 is better way to solve this.
