### ISSUE TITLE
define an encoding-independent "ypath:1.0" type

### ISSUE THREAD

**Issue by kwatsen** [netmod-wg/yang-next#55]
Not sure if the title is correct, but this issue regards the discussion from the rather long thread:

[[netmod] xpath expressions in JSON](https://mailarchive.ietf.org/arch/msg/netmod/5qRC1VqO58b7vXbNm3DVednpxtY)

Cherry picking a few comments...

Martin writes:
> > If we bother to fix this problem at all, then we should get rid of reliance
> > on prefix to namespace mappings.
> 
> Long-term, yes!

Andy writes:
> I guess we will have this debate for real if YANG 2.0 is ever done

Martin writes:
> (This said, I would like to have a context-independent encoding of all
> YANG types in the future.  But not now.)
> 

Rob writes:
> I can live with that.  But still strongly think that WG should think of
> trying to move YANG on from Xpath 1.0.

Martin writes:
> [This context-dependent encoding that we have for a couple of types is
> probably the biggest mistake in YANG]

Lada writes:
> This is impossible if we want to call it XPath. With an explicit
> namespace/prefix declaration, for example
> 
>   "namespace": [
>     {
>       "prefix": "if",
>       "uri": "urn:ietf:params:xml:ns:yang:ietf-interfaces",
>       "default": true
>     },
>     {
>       "prefix": "ip",
>       "uri": "urn:ietf:params:xml:ns:yang:ietf-ip"
>     }
>   ]
> 
> it would be
> 
>   /interfaces/interface[name='eth0']/ip:ipv4
> 
> which is not too bad either.

**Comment by mbj4668** [comment]
There's another issue (#22) for restricting xpath.

I think that we came to an agreement that the current xpath1.0 type can be made to be context-independent.  Also, the necessary text would go into 6991bis, so no changes to YANG are needed for this.

See also #56.

**Comment by kwatsen** [comment]
Closed in Virtual Interim.
See Martin's last comment.
