### ISSUE TITLE
Clarify if double quotes are needed around identifiers

### ISSUE THREAD

**Issue by mjethanandani** [netmod-wg/yang-next#64]
The usage of double quotes around string arguments is not clear. Clearly, if the string involves expressions that include white spaces, double quotes are needed. However, what if the string is nothing but a identity defined in the same or another module? Are double quotes needed around identities. Take this for an example:
````
module foo {
    identity bar {
      description "Base definition.";
    }
    identity foo-bar {
      base bar;
    }

    leaf blah {
      type identityref {
        base bar;
      }
      default "foo-bar"; // are double quotes needed here?
  }
}
````

**Comment by mbj4668** [comment]
See section 6.3, 6.1.2 and 6.1.3.  I'm all for clarifications though!
The following are all equivalent:

    default "foo-bar";
    default 'foo-bar';
    default foo-bar;
    default 'f'+'o'+"o"
    +                    "-b"
           + "ar";

**Comment by kwatsen** [comment]
I think motivation is more to restrict the grammar so that quotes MUST be present in some cases and MUST NOT be present in others. 

Currently `pyang -f yang --keep-comments` adds and/removes quotes to otherwise **valid** modules.

**Comment by mbj4668** [comment]
I don't think we should restrict the grammar.  The simplicity (no special rules _at all_; all statements are on the same form) is goodness.
pyang -f yang is in a sense a "prettyfier".  It parses the module (yin or yang format) and outputs a valid YANG module.  It has to choose some quote character, as well as indentation style, line breaks, order of statements etc.

**Comment by mjethanandani** [comment]
If simplicity is the guiding principle with no special rules, why change the statement if it is correct?

On the other hand, if the argument is for trying to make the model pretty, pick or state what the "default" is so all validators/parsers can follow.

**Comment by abierman** [comment]
Why is this even an issue?
A string without any whitespace and special chars does not need quotes.
Not just identifiers -- any string (e.g.r range-stmt)
Quotes on identifiers would make them less readable.
Since identifiers are never allowed to contain whitespace or special chars,
there is no value in using quotes on them

**Comment by mbj4668** [comment]
> On the other hand, if the argument is for trying to make the model pretty, pick or state what the "default" is so all validators/parsers can follow.

Ok, but this is not a YANG next issue.  It is a question of the consistent format that the RFC editor enforces when the IETF publsihes YANG modules.  I suggest we close this issue here.

**Comment by immibis** [comment]
Agree with Martin. There is a clean separation of layers here. If you're writing a YANG processor, the parser reads the input and converts it into a canonical string form in your AST, and then when interpreting the AST you don't need to know whether there were quotes or not.

**Comment by kwatsen** [comment]
Martin's goal is to have a prettifier, which is goodness.

Martin has a specific prettifier (`pyang -f yang --keep-comments`) that is currently being used by the RFC Editors to change to layout of modules.

While there are aspects about this that I disagree with, the questions at hand are:

1. Should a "pretty" format be documented, so that other tools can generate it too?
      - something like PEP-8 (Style Guide for Python Code)
      - note: this by itself is NOT a YANG-Next issue

2. If "yes", should some of this documentation be pushed into the YANG grammar (ABNF)?
      - e.g., Python asserts indenting, but doesn't assert the indent amount
      - introducing such restrictions IS a YANG-Next issue and, of course, would be backcompat-low.

**Comment by rgwilton** [comment]
I don't think that we need to standardize the format of pretty YANG.  I think that we can just close this issue.

**Comment by abierman** [comment]
It is good that YANG is working on tooling.
Not every detail needs an RFC.

Even RFC 8407 avoids specifying quoting rules, although every example shows
identifiers as unquoted.  Examples show revision dates as quoted, even though
there is no need to quote them.

**Comment by kwatsen** [comment]
Agreement not to change grammar.  Thus not a YANG-next issue.
