### ISSUE TITLE
add 'unique' as a substatement to 'leaf-list'

### ISSUE THREAD

**Issue by kwatsen** [netmod-wg/yang-next#79]
Sometimes the values of a leaf-list should be unique, but there's no way to express that currently.

**Comment by mbj4668** [comment]
RFC 7950 says:
    In configuration data, the values in a leaf-list MUST be unique.

Do you mean that you want to indicate that all values in a config false leaf-list must be unique?

**Comment by kwatsen** [comment]
Ah, never mind then.  Closing.
