### ISSUE TITLE
enable specifying augmentation's location amongst siblings

### ISSUE THREAD

**Issue by kwatsen** [netmod-wg/yang-next#87]
When augmenting a grouping, the augmented nodes are floated to the bottom on the resolved definition.  While YANG trees are unordered,  it would be nice to be able to control tree-diagram output.  Many times items that are augmented in should logically be at the top and co-located with like siblings...

**Comment by abierman** [comment]
Do not support.
Augmented nodes are unordered and it would be a big change to the implementations
to enforce some augment order.  There is no order for top-level data nodes either.
Tree diagram output not important.

**Comment by janlindblad** [comment]
Agree that we should not introduce order in the language. We could add annotations for or cli flags to pyang -f tree, tho.
